print ("Your name:")
name = input()
print ("Your age:")
age = input()
print ("Your course code:")
course_code = input()
print ("Name:", name, type(name), "\nAge:", age, type(age), "\nCourse Code:", course_code, type(course_code))